package util

const ADMIN_TYPE = "ADMIN_TYPE"
const USER_TYPE = "USER_TYPE"

const ADMIN_AUTH_MENU = "ADMIN_AUTH_MENU"
const ADMIN_REGISTER_MENU = "ADMIN_REGISTER_MENU"
const ADMIN_LOGIN_MENU = "ADMIN_LOGIN_MENU"
const ADMIN_AUTH_MENU_BACK = "BACK"
const ADMIN_APPROVAL_MENU = "ADMIN_APPROVAL_MENU"
const ADMIN_APPROVE_REJECT_MENU = "ADMIN_APPROVE_REJECT_MENU"

const USER_AUTH_MENU = "USER_AUTH_MENU"
const USER_AUTH_REGISTER_MENU = "USER_AUTH_REGISTER_MENU"
const USER_AUTH_LOGIN_MENU = "USER_AUTH_LOGIN_MENU"
const USER_AUTH_BACK_MENU = "USER_AUTH_BACK_MENU"

const USER_SUB_MENU = "USER_SUB_MENU"
const USER_SUB_MENU_SEND_EMAIL = "USER_SUB_MENU_SEND_EMAIL"
const USER_SUB_MENU_INBOX = "USER_SUB_MENU_INBOX"
const USER_SUB_MENU_OUTBOX = "USER_SUB_MENU_OUTBOX"
const USER_SUB_MENU_LOGOUT = "USER_SUB_MENU_LOGOUT"

const BACK = "BACK"

const PRINT_STATUS_SUCCESS = "PRINT_STATUS_SUCCESS"
const PRINT_STATUS_ERROR = "PRINT_STATUS_ERROR"
const PRINT_STATUS_NOTHING = "PRINT_STATUS_NOTHING"
